export enum ValidateProfileErrors {
	INCORRECT_USER_DATA = 'INCORRECT_USER_DATA',
	INCORRECT_USER_AGE = 'INCORRECT_USER_AGE',
	INCORRECT_USER_COUNTRY = 'INCORRECT_USER_COUNTRY',
	NO_USER_DATA = 'NO_USER_DATA',
	SERVER_ERROR = 'SERVER_ERROR'
}
